spring.application.name=ZestStore

# ==============================================
# SQL Server
# ==============================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=PoloShopDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==============================================
# JPA / Hibernate
# ==============================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# ==============================================
# JWT
# ==============================================
app.jwt.secret=ZestStoreSecretKey2026ForJWTTokenGenerationMustBe256BitsLong
app.jwt.expiration=86400000

# ==============================================
# File upload
# ==============================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=D:/ZEST_Store/uploads

# ==============================================
# Server
# ==============================================
server.port=8080

# ==============================================
# Logging
# ==============================================
logging.level.com.example.zeststore.security=DEBUG

# SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email ch? c?a hàng (ch? s?a ???c trong file này)
app.admin.email=kiwmtawn26@gmail.com
